trigger: none
pr: none

stages:
  - template: ../../../../build/azp/azure-pipelines.stages.yml
    parameters:
      configurations:
        - name: [ 'samples', 'machines', 'multiple', 'server' ]
          machines: [ 'windows', 'linux' ]
          providers: [ 'virtualbox', 'hyperv' ]
