trigger:
  branches:
    include:
      - "*"
  tags:
    include:
      - "*"
  paths:
    include:
      - samples/machines/multiple/linux
pr: none

stages:
  - template: ../../../../build/azp/azure-pipelines.stages.yml
    parameters:
      configurations:
        - name: ["samples", "machines", "multiple", "linux"]
          machines: ["server", "desktop", "docker"]
          providers: ["virtualbox", "hyperv"]
