trigger:
  branches:
    include:
      - "*"
  tags:
    include:
      - "*"
  paths:
    include:
      - samples/machines/single/linux
pr: none

stages:
  - template: ../../../../build/azp/azure-pipelines.stages.yml
    parameters:
      configurations:
        - name: ["samples", "machines", "single", "linux"]
          machines: ["default"]
          providers: ["virtualbox", "hyperv"]
