pr: none

stages:
  - stage: commit
    displayName: Commit

    jobs:
      - template: ./build/azp/commit.build.yml
        parameters:
          samples:
            - machines
            - providers
            - provisioners
