trigger: none
pr: none

stages:
  - stage: commit
    displayName: Commit

    jobs:
      - job: build
        displayName: Build

        pool:
          name: Default
          demands:
            - AZP_AGENT_VAGRANT

        workspace:
          clean: all

        steps:
          - script: |
              vagrant --version
            displayName: Init

          - script: |
              cd ./samples/machines
              vagrant status
            displayName: Test
