version: '3'

services:
  rubocop:
    build:
      context: ./build/docker
      dockerfile: ./rubocop.Dockerfile
    volumes:
      - .:/opt/gusztavvargadr/rubocop
    working_dir: /opt/gusztavvargadr/rubocop

  vagrant:
    build:
      context: ./build/docker
      dockerfile: ./vagrant.Dockerfile
    volumes:
      - .:/opt/gusztavvargadr/vagrant
    working_dir: /opt/gusztavvargadr/vagrant
