trigger:
  branches:
    include:
      - "*"
  tags:
    include:
      - "*"
  paths:
    include:
      - samples/provisioners/core/windows
pr: none

stages:
  - template: ../../../../build/azp/azure-pipelines.stages.yml
    parameters:
      configurations:
        - name: ["samples", "provisioners", "core", "windows"]
          machines: ["default"]
          providers: ["virtualbox", "hyperv"]
