---
defaults:
  machines:
    core: &machine_core
      providers:
        virtualbox:
        hyperv:

environment: docker.provisioning.samples.vagrant

machines:
  linux:
    <<: *machine_core
    box: gusztavvargadr/u16s-dc
    provisioners:
      docker:
        builds:
          - path: /vagrant
            args: -t hello-world:local
        runs:
          - name: hello-world-local
            image: hello-world:local
            daemonize: false
            restart: no
      shell:
        path: run.sh
  windows:
    <<: *machine_core
    box: gusztavvargadr/w16sc-de
    provisioners:
      shell:
        path: run.ps1
