trigger:
  branches:
    include:
      - "*"
  tags:
    include:
      - "*"
  paths:
    include:
      - samples/providers/hyperv/windows
pr: none

stages:
  - template: ../../../../build/azp/azure-pipelines.stages.yml
    parameters:
      configurations:
        - name: ["samples", "providers", "hyperv", "windows"]
          machines: ["default"]
          providers: ["hyperv"]
