trigger:
  branches:
    include:
      - '*'
  tags:
    include:
      - '*'
  paths:
    include:
      - samples/machines/single/windows
pr: none

stages:
  - template: ../../../../build/azp/azure-pipelines.stages.yml
    parameters:
      configurations:
        - name: [ 'samples', 'machines', 'single', 'windows' ]
          machines: [ 'default' ]
          providers: [ 'virtualbox', 'hyperv' ]
